#!/bin/bash

if [[ $# -ne 1 ]];
then
	echo "usage: $0 [FILENAME]";
	exit 0;
fi;


mako_fnum=`find mako/mako/ -type f | wc -l`

mako_lines=`wc $(find mako/mako/ -type f) -l | tail -1 | \
	sed -E "s/^\s*([0-9]*).*/\1/g"`


jinja_fnum=`find jinja/jinja2/ -type f | wc -l`

jinja_lines=`wc $(find jinja/jinja2/ -type f) -l | tail -1 | \
	sed -E "s/^\s*([0-9]*).*/\1/g"`


pycro_fnum=`find pycro/pycro -type f | wc -l`

pycro_lines=`wc $(find pycro/pycro -type f) -l | tail -1 | \
	sed -E "s/^\s*([0-9]*).*/\1/g"`


preprocess_fnum=`find preprocess/lib/ -type f | wc -l`

preprocess_lines=`wc $(find preprocess/lib/ -type f) -l | tail -1 | \
	sed -E "s/^\s*([0-9]*).*/\1/g"`


cat > $1 << EOT

> all of these statistics automatically generated by \`$0\` script file.

# Comparsion of template engines:

| engines					| files No. 		| lines No.
| ---						| ---				| ---
| [mako][]					| $mako_fnum		| $mako_lines
| [jinja][]					| $jinja_fnum		| $jinja_lines
| [pycro][]					| $pycro_fnum		| $pycro_lines
| [preprocess][]			| $preprocess_fnum 	| $preprocess_lines

[mako]: 		https://github.com/sqlalchemy/mako
[jinja]: 		https://github.com/pallets/jinja
[pycro]: 		https://github.com/mak12776/pycro
[preprocess]: 	https://github.com/trentm/preprocess

EOT

echo "['$1' created!]";

